services:
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.caddy/Caddyfile.dev:/etc/caddy/Caddyfile:rw
    networks:
      - proxy_network
    depends_on:
      - timmypidashev.dev
      
  watchtower:
    container_name: updates
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 120 --cleanup --label-enable

  timmypidashev.dev:
    container_name: timmypidashev
    image: ghcr.io/timmypidashev/timmypidashev.dev:latest
    networks:
      - proxy_network

networks:
  proxy_network:
    name: proxy_network
    external: true
