version: '3.8'

services:
  proxy:
    container_name: proxy
    image: caddy:latest
    ports:
      - 80:80
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:rw
    restart: always
    networks:
      - external
    depends_on:
      - landing

  landing:
    container_name: landing
    image: landing:dev
    volumes:
      - ./src/landing:/app
    expose:
      - 3000
      - 8000
    networks:
      - external

networks:
  external:
    name: external
    driver: bridge
