version: '3.8'

services:
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:rw
    restart: always
    networks:
      - caddy
    depends_on:
      - landing
      - about

  landing:
    container_name: landing
    image: landing:dev
    volumes:
      - ./src/landing/landing:/app/landing
      - ./src/landing/assets:/app/assets
      - ./src/landing/rxconfig.py:/app/rxconfig.py
    networks:
      - caddy

  about:
    container_name: about
    image: about:dev
    volumes:
      - ./src/about/about:/app/about
      - ./src/about/assets:/app/assets
      - ./src/about/rxconfig.py:/app/rxconfig.py
    networks:
      - caddy

networks:
  caddy:
    name: caddy
    external: true
