#!/bin/bash

# Commandline args
action="$1"
environment="$2"

# Set the build arguments as environment variables
export BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
export GIT_COMMIT=$(git rev-parse --short HEAD)


case $action in
    build)
        if [ "$environment" == "dev" ];
        then
            echo "build dev"
        
        elif [ "$environment" == "prod" ];
        then
            echo "build prod"
        
        else
            echo "Invalid environment. Use 'dev' or 'prod'!"
            exit 1
        fi
        ;;

    run)
        if [ "$environment" == "dev" ];
        then
            echo "run dev"
        
        elif [ "$environment" == "prod" ];
        then
            echo "run prod"

        else
            echo "Invalid environment. Use 'dev' or 'prod'!"
            exit 1
        fi
        ;;
    *)
        echo "Invalid action. Use 'build', 'run', or 'push'!"
        ;;
esac
