# Imported args
ARG BUILD_DATE
ARG GIT_COMMIT
ARG DNS_VERSION

# Print the values of the build arguments
RUN echo "DNS_VERSION=$DNS_VERSION"

# CoreDNS base image
ARG ALPINE_VERSION=3.18
ARG GO_VERSION=1.21.3
ARG COREDNS_VERSION=v1.11.1

FROM golang:${GO_VERSION}-alpine${ALPINE_VERSION} AS builder
RUN apk add -q --progress --update --no-cache git ca-certificates libcap2-bin

ENV GO111MODULE=on \
    CGO_ENABLED=0

go install github.com/coredns/coredns/tree/v1.11.1
